# File: .readthedocs.yaml

version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

#conda:
#  environment: docs/environment.yml

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt