% Construct a questdlg with three options
hm=pwd;

choice = questdlg(sprintf('Do you really want to clear all files that were generated by runIEC.m %s?',hm), ...
    'Clear all files associated with runIEC.m', ...
    'Yes','No','No');
% Handle response
switch choice
    case 'Yes'
        cd('wind')
        delete *
        cd(hm)
        
        cd('out')
        delete *
        cd(hm)
        
        cd('rcc')
        delete *
        cd(hm)
        
        delete *.out
        delete *.elm
        delete IEC*.ipt
        delete IEC*.fst
        delete IEC*.opt
        delete IEC*.ipt
        delete IEC*.fsm
        
        delete spans.mat
        delete rccdata.mat
        delete output.mat
        
        disp('wind\, out\, rcc\, ipt, fst, opt, fsm, elm, out and some mat files all have been deleted.')
        
    case 'No'
        disp('ClearAllFiles aborted prior to delete.')
end



