import unittest
from os.path import abspath, dirname, join

from pynumad.objects.Airfoil import Airfoil

testdir = dirname(abspath(str(__file__)))
test_datadir = join(testdir, "test_data")

class TestAirfoil(unittest.TestCase):
    @classmethod
    def setUpClass(self):
        self.xmlfile = join(test_datadir,'airfoils/DU91-W-250.txt')

    def test_load_xml(self):
        x = Airfoil(filename = self.xmlfile)

        #check reference
        self.assertEqual(x.reference,'Points generated by BRR for NuMAD, 6/2/2011')

        #TODO: check coords

if __name__ == "__main__":
    unittest.main()