fn='63-235'; % filename of excel file with DESIGNFOIL coords
reftext='Coords generated by DESIGNFOIL R6.44 on 27 Feb 2012.  NACA 63-235 a=1.0.';

[num,txt,raw]=xlsread([fn '.xlsx']);

coords =[num(end:-1:2,2) num(end:-1:2,3)];
coords2=[num(end:-1:1,2) num(end:-1:1,3)];

for i=1:length(coords)
    plot(coords(1:i,1),coords(1:i,2),'k-o')
    axis equal
    axis([0 1 -.4 .4])
    title({'VERIFY:','NuMAD coords must start at TE, cover HP, Nose, LP, then end at TE'})
    drawnow
    pause(0.02)
end

writeNuMADAirfoil(coords,reftext,[fn '.txt']);

fid=fopen([fn '.xfoil.txt'],'wt');
fprintf(fid,'%8.6f  %8.6f\n',coords2');
fclose(fid);
