# File: docs/environment.yaml

name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - sphinx==4.1.2
  - pip:
    - sphinx_rtd_theme==0.5.2
    - sphinxcontrib-bibtex==2.3.0
    - sphinxcontrib-matlabdomain==0.12.0
    - sphinxext-remoteliteralinclude==0.3.0
    