# File: docs/environment.yaml

name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - click==8.0.1
  - colorama==0.4.4
  - colorclass==2.2.0
  - future==0.18.2
  - git==2.33.0
  - pip==21.2.4
  - sphinx_rtd_theme==0.5.2
  - sphinxcontrib-bibtex==2.3.0
  - pip:
    - sphinx-multiversion==0.2.4
    - sphinxcontrib-matlabdomain==0.12.0
    - sphinxext-remoteliteralinclude==0.3.0
